name: ansible-lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "stable"
      - "release/v*"
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "--skip-list internal-error site.yml"
          setup_python: "true"
          requirements_file: "./requirements.yml"
